GET localhost:8080/api/test

###

GET localhost:8080/api/items-management/fetch

###

POST localhost:8080/api/items-management/add
Content-Type: application/json

[
  {
    "item": {
      "id": "item1",
      "name": "First Item",
      "description": "Cool First Item",
      "price": 20,
      "cost": 10
    },
    "quantity": 30
  },
  {
    "item": {
      "id": "item2",
      "name": "Second Item",
      "description": "Cool Third Item",
      "price": 100,
      "cost": 90
    },
    "quantity": 5
  }
]

###

DELETE localhost:8080/api/items-management/delete
Content-Type: application/json

{
  "itemIds": ["item1"]
}