GET localhost:8080/api/test

###

GET localhost:8080/api/items-management/fetch

###

POST localhost:8080/api/items-management/add
Content-Type: application/json

[
  {
    "id": 1,
    "item": {
      "name": "First Item",
      "description": "Cool First Item",
      "price": 100,
      "cost": 90
    },
    "quantity": 5
  },
  {
    "id": 2,
    "item": {
      "name": "Second Item",
      "description": "Cool Second Item",
      "price": 20,
      "cost": 10
    },
    "quantity": 30
  }
]

###

DELETE localhost:8080/api/items-management/delete
Content-Type: application/json

{
  "itemIds": [1]
}