GET localhost:8080/api/internal/offer/test

###

POST localhost:8080/api/upload/offers
Content-Type: application/json

[
  {
    "id": "offer1",
    "name": "Buy 1 Get 1 Free!",
    "itemId": "item1",
    "priceReduction": 10,
    "description": "Buy Item1 and Get another for FREE",
    "quantityThreshold": 5
  },
  {
    "id": "offer2",
    "name": "Flash Sale 50%",
    "itemId": "item2",
    "priceReduction": 5,
    "description": "Amazing Flash deal Available on Item 2",
    "quantityThreshold": 10
  }
]

###

DELETE localhost:8080/api/delete/offers
Content-Type: application/json

{
  "offerIds": ["offer1"]
}