GET localhost:8080/api/orders?values=order2,order4

###

POST localhost:8080/api/orders/place
Content-Type: application/json

[
  {
    "id": "order1",
    "orderItems": [
      {
        "id": "item1",
        "name": "First Item",
        "originalPrice": 100,
        "discountedPrice": 90
      },
      {
        "id": "item2",
        "name": "Second Item",
        "originalPrice": 50,
        "discountedPrice": 45
      }
    ],
    "orderOffers": [
      {
        "itemId": "item1",
        "priceReduction": 10,
        "quantityThreshold": 2
      },
      {
        "itemId": "item2",
        "priceReduction": 5,
        "quantityThreshold": 2
      }
    ]
  }
]
