openapi: 3.0.0
tags:
  - name: public
    description: For public use
info:
  title: orders-api
  version: '1.0'
  description: Supports ordering flow for public API consumers
  contact:
    name: SadaPay Recruiting
servers:
  - url: 'http://localhost:3004'
    description: Orders API
paths:
  /orders:
    post:
      summary: place orders
      tags:
        - public
      operationId: post-orders
      responses:
        '200':
          $ref: '#/components/responses/post-orders-response'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orders:
                  type: array
                  items:
                    $ref: '#/components/schemas/order'
              required:
                - orders
        description: ''
      description: Place orders
    get:
      summary: get orders
      tags:
        - public
      operationId: get-orders
      responses:
        '200':
          $ref: '#/components/responses/get-orders-response'
      parameters:
        - schema:
            type: array
          in: query
          name: orderIds[]
          required: true
          description: order IDs to get
      description: Get orders by ID
    parameters: []
components:
  schemas:
    order-item:
      title: order-item
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        originalPrice:
          type: number
        discountedPrice:
          type: number
      required:
        - id
        - originalPrice
        - discountedPrice
    order-offer:
      title: order-offer
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        itemId:
          type: string
        priceReduction:
          type: number
        quantityThreshold:
          type: integer
      required:
        - id
        - name
        - itemId
        - priceReduction
    order:
      title: order
      type: object
      properties:
        id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/order-item'
        offers:
          type: array
          items:
            $ref: '#/components/schemas/order-offer'
      required:
        - id
        - items
        - offers
  responses:
    post-orders-response:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              orders:
                type: array
                items:
                  $ref: '#/components/schemas/order'
            required:
              - orders
          examples:
            success-example:
              $ref: '#/components/examples/post-orders-success-example'
    get-orders-response:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              orders:
                type: array
                items:
                  $ref: '#/components/schemas/order'
            required:
              - orders
          examples:
            success-example:
              $ref: '#/components/examples/get-orders-success-example'
  parameters:
    order-id:
      name: order-id
      in: path
      required: true
      schema:
        type: string
  examples:
    get-orders-success-example:
      value:
        description: GET orders success example
        orders:
          - id: order1
            items:
              - id: item1
                name: Item 1
                originalPrice: 1.5
                discountedPrice: 0.75
              - id: item2
                name: Item 2
                originalPrice: 9.99
                discountedPrice: 9.99
              - id: item2
                name: Item 2
                originalPrice: 9.99
                discountedPrice: 0
            offers:
              - id: offer1
                name: Half-price
                itemId: item1
                priceReduction: 0.5
                quantityThreshold: 1
              - id: offer2
                name: Buy 1 get 1
                itemId: item2
                priceReduction: 1
                quantityThreshold: 2
    post-orders-success-example:
      value:
        description: POST orders success example
        orders:
          - id: order1
            items:
              - id: item1
                name: Item 1
                originalPrice: 1.5
                discountedPrice: 0.75
              - id: item2
                name: Item 2
                originalPrice: 9.99
                discountedPrice: 9.99
              - id: item2
                name: Item 2
                originalPrice: 9.99
                discountedPrice: 0
            offers:
              - id: offer1
                name: Half-price
                itemId: item1
                priceReduction: 0.5
                quantityThreshold: 1
              - id: offer2
                name: Buy 1 get 1
                itemId: item2
                priceReduction: 1
                quantityThreshold: 2
